name: Lint and Test Charts
on: push
# on: pull_request

jobs:
  lint-test:
    runs-on: ubuntu-latest
    env:
      remote_url: https://github.com/rancher/helm3-charts.git
      # Chart-testing parameters
      ct_remote: rancher-helm3-charts
      ct_target_branch: master
      ct_debug: false
      ct_print_config: true
      ct_validate_maintainers: false
      ct_check_version_increment: false
      ct_namespace: default
      ct_chart_dirs: $(find charts -type d -mindepth 1 -maxdepth 1 | paste -sd ',')
      ct_chart_repos: "\
        stable=https://charts.helm.sh/stable,\
        incubator=https://charts.helm.sh/incubator"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # chart-testing requires a full clone
          fetch-depth: 0

      - name: Set up Rancher remote
        run: >
          git remote add ${{ env.ct_remote }} ${{ env.remote_url }}
          --fetch
          --track ${{ env.ct_target_branch }}

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.0.1

      - name: Run chart-testing [ct list-changed]
        id: list-changed
        run: >
          changed=$(
          ct list-changed
          --remote ${{ env.ct_remote }}
          --target-branch ${{ env.ct_target_branch }}
          --chart-dirs ${{ env.ct_chart_dirs }}
          )

          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          else
            echo "No chart changes detected, skipping tests."
          fi

      - name: Run chart-testing [ct lint]
        if: steps.list-changed.outputs.changed == 'true'
        run: >
          ct lint
          --remote ${{ env.ct_remote }}
          --target-branch ${{ env.ct_target_branch }}
          --debug=${{ env.ct_debug }}
          --print-config=${{ env.ct_print_config }}
          --validate-maintainers=${{ env.ct_validate_maintainers }}
          --check-version-increment=${{ env.ct_check_version_increment }}
          --chart-repos ${{ env.ct_chart_repos }}
          --chart-dirs ${{ env.ct_chart_dirs }}

      - name: Create kind cluster
        if: steps.list-changed.outputs.changed == 'true'
        uses: helm/kind-action@v1.0.0

      - name: Run chart-testing [ct install]
        if: steps.list-changed.outputs.changed == 'true'
        continue-on-error: true
        run: >
          ct install
          --namespace ${{ env.ct_namespace }}
          --remote ${{ env.ct_remote }}
          --target-branch ${{ env.ct_target_branch }}
          --print-config=${{ env.ct_print_config }}
          --debug=${{ env.ct_debug }}
          --chart-repos ${{ env.ct_chart_repos }}
          --chart-dirs ${{ env.ct_chart_dirs }}
  # lint-charts:
  #   name: Lint Charts
  #   runs-on: ubuntu-latest
  #   container:
  #     image: quay.io/helmpack/chart-testing:latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #       with:
  #         # Needed for ct lint to work, a shallow clone will cause it to fail.
  #         fetch-depth: 0
  #     - name: Run ct lint (charts)
  #       uses: ./.github/actions/ct-lint
  #       with:
  #         remote: rancher-helm3-charts
  #         remote_url: https://github.com/rancher/helm3-charts.git
  #         target_branch: master
  #         ct_debug: false
  #         ct_print_config: true
  #         ct_validate_maintainers: false
  #         ct_chart_dirs: $(find charts -type d -mindepth 1 -maxdepth 1 | paste -sd ',')
  #         ct_chart_repos: "\
  #           stable=https://charts.helm.sh/stable,\
  #           incubator=https://charts.helm.sh/incubator"

#
#
# lint-charts-draft:
#   name: Lint charts
#   runs-on: ubuntu-latest
#   container:
#     image: quay.io/helmpack/chart-testing:latest
#   env:
#     remote: rancher-charts
#     remote_url: https://github.com/rancher/charts.git
#     target_branch: master
#     ct_debug: false
#     ct_print_config: true
#     ct_validate_maintainers: false
#     ct_chart_dirs: find charts -type d -mindepth 1 -maxdepth 1 | paste -sd ','
#     ct_chart_repos: "\
#       stable=https://charts.helm.sh/stable,\
#       incubator=https://charts.helm.sh/incubator"
#   steps:
#     - name: Checkout
#       uses: actions/checkout@v2
#       with:
#         # Needed for ct lint to work as the default behavior is a shallow clone
#         fetch-depth: "0"
#     - name: Log ct version
#       run: ct version
#     - name: Add rancher-charts remote and fetch master
#       run: git remote add --fetch --track master rancher-charts https://github.com/rancher/charts.git
#     - name: ct lint charts
#       run: >
#         ct lint
#         --remote ${{ env.remote }}
#         --target-branch ${{ env.target_branch }}
#         --validate-maintainers=${{ env.ct_validate_maintainers }}
#         --print-config=${{ env.ct_print_config }}
#         --debug=${{ env.ct_debug }}
#         --chart-repos ${{ env.ct_chart_repos }}
#         --chart-dirs $(${{ env.ct_chart_dirs }})
# lint-charts-draft3:
#   name: Lint charts 3
#   runs-on: ubuntu-latest
#   container:
#     image: quay.io/helmpack/chart-testing:latest
#   steps:
#     - name: Checkout
#       uses: actions/checkout@v2
#     - name: lint charts
#       uses: ./.github/actions/ct-lint
#       with:
#         remote: value-passed-in
